name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create Directories
      run:
          mkdir -p dist
          
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if required)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (if required)
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS S3 (example task)
      run: aws s3 sync ./dist s3://my-bucket-name --delete
